version: "3.9"

services:
  tracker:
    build: .
    # override to run tracker.py
    entrypoint: ["python","tracker.py"]
    ports:
      - "9090:9090"
    networks:
      - p2pnet

  peer:
    build: .
    # peer.py is the default via your Dockerfile
    entrypoint: ["python","peer.py"]
    volumes:
      - ./peers:/app/peers   # read-write so each peer writes into peers/peerX/music
    networks:
      - p2pnet

networks:
  p2pnet:
    driver: bridge
    name: p2pnet
