services:
  tracker:
    build: .
    entrypoint: ["python","tracker.py"]
    ports:
      - "9090:9090"
    networks:
      - p2pnet

  peer:
    build: .
    entrypoint: ["python","peer.py"]
    volumes:
      - ./peers:/app/peers
    networks:
      - p2pnet

networks:
  p2pnet:
    driver: bridge
    name: p2pnet
